# Generated by Django 5.2.15 on 2026-06-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qtaker",
            name="last_answer_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
