# Generated by Django 5.2.15 on 2026-06-14 01:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True, default="")),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="coaches/"),
                ),
                ("photo_url", models.URLField(blank=True, default="")),
                (
                    "specialization",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_special", models.BooleanField(default=False)),
                (
                    "rank_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("hourly_rate", models.PositiveIntegerField(blank=True, null=True)),
                ("achievements", models.JSONField(blank=True, default=list)),
                ("special_bio", models.TextField(blank=True, default="")),
                ("featured_order", models.PositiveIntegerField(blank=True, null=True)),
                ("points_cost", models.PositiveIntegerField(default=1)),
                ("meeting_link", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coach",
                "verbose_name_plural": "Coaches",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_name", models.CharField(max_length=255)),
                ("student_email", models.EmailField(max_length=254)),
                (
                    "student_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("booking_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "course_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("expert", "Expert"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("recurring_days", models.JSONField(blank=True, default=list)),
                ("recurring_dates", models.JSONField(blank=True, default=list)),
                (
                    "monthly_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("sessions_per_month", models.PositiveIntegerField(default=4)),
                (
                    "booking_mode",
                    models.CharField(
                        choices=[("single", "Single"), ("double", "Double")],
                        default="single",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="scheduling.coach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Booking",
                "verbose_name_plural": "Monthly Bookings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AvailabilitySlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Sunday"),
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to="scheduling.coach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Availability Slot",
                "verbose_name_plural": "Availability Slots",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="FlexibleBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Sunday"),
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                        ]
                    ),
                ),
                ("points_used", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("refund_processed", models.BooleanField(default=False)),
                ("meeting_link", models.URLField(blank=True, default="")),
                ("coach_notes", models.TextField(blank=True, default="")),
                ("student_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flexible_bookings",
                        to="scheduling.coach",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flexible_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Flexible Booking",
                "verbose_name_plural": "Flexible Bookings",
                "ordering": ["-session_date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="SpecialBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_name", models.CharField(max_length=255)),
                ("student_email", models.EmailField(max_length=254)),
                (
                    "student_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("total_sessions", models.PositiveIntegerField()),
                ("sessions_completed", models.PositiveIntegerField(default=0)),
                ("session_dates", models.JSONField(default=list)),
                ("is_recurring", models.BooleanField(default=False)),
                ("recurring_days", models.JSONField(blank=True, default=list)),
                ("recurring_weeks", models.PositiveIntegerField(default=4)),
                ("hourly_rate", models.PositiveIntegerField()),
                ("total_amount", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("payment_received", "Payment Received"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_bookings",
                        to="scheduling.coach",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="special_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Special Booking",
                "verbose_name_plural": "Special Bookings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CoachBlockedDate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("blocked_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_dates",
                        to="scheduling.coach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coach Blocked Date",
                "verbose_name_plural": "Coach Blocked Dates",
                "ordering": ["-blocked_date"],
                "unique_together": {("coach", "blocked_date", "start_time")},
            },
        ),
    ]
