# Generated by Django 5.2.15 on 2026-06-16 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "parent_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "parent_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("school", models.CharField(blank=True, default="", max_length=255)),
                ("chess_rating", models.PositiveIntegerField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "ordering": ["user__email"],
            },
        ),
    ]
