# Generated by Django 5.2.15 on 2026-06-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='points_cost',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
